### ISSUE TITLE
Lazily build the handler

### ISSUE THREAD

**Issue by guhemama** [doppiogancio/mocked-client#28]
Problem: I want to share the same mocked client with different clients, but do not want to add all routes when building the client. I would like instead to share the `HandlerBuilder`  and call `addRoute` on each test case, but not to rebuild the entire client.

Possible solution: by lazily building the handler when the request is called, we can add routes at any time without breaking backwards compatibility.

**Comment by doppiogancio** [comment]
Correct, you can already create a shared HandlerBuilder and add specific routes before building the client. A lazy builder is a great idea. Consider that now building the handler means returning a callback. Maybe we could return a class instead, with an invoke method. Maybe the class returned should be the HandlerBuilder itself, which has already methods to add routes. Last suggestion, since we can not change the "HTTP Client" to expose a method called "getHandlerBuilder", I recommend keeping in a variable the HandlerBuilder instance, in order to add new routes at any moment.
